/**
 * TypeScript Language
 * - It is a programming language that is a superset of JavaScript
 * - It provides
 *      - Static Typing to variables, parameters, return types, etc.
 *      - Organization of codes through class, interface, namespace, module, etc.
 *      - Tooling for static type analysis, detecting errors, unused data, unreachable code, debugging, etc.
 */

/**
 * TypeScript Compiler
 * - It converts TypeScript source file into JavaScript source file
 * - Its steps involved
 *      - TypeScript source file is parsed into AST (Abstract Syntax Tree - A data structure describing the program)
 *      - AST is then typechecked whether it conform to the TypeScript rule or not
 *      - If it conform to the TypeScript rule, JavaScript source file is generated from the AST
 *          - JavaScript source file can then be evaluated by the engine where it steps involved
 *              - Parsing JavaScript source file into AST
 *              - Bytecode is produced from the AST
 *              - Bytecode is evaluated by the runtime
 * - Its command-line application is `tsc`
 *      - It is installed through `npm` preferably at the project level
 *      - It uses `tsconfig.json` generated by `tsc --init` for its compiling configuration
 */

/**
 * TypeScript Type Annotation
 * - It support
 *      - Explicitly annotating the type
 *      - Inferred automatically from value
 */

// Explicit Type Annotation
let a: number = 20;
let b: string = 'hello';
let c: boolean[] = [ true, false ];

// Automatic Type Inference
let d = 20;
let e = 'hello';
let f = [true, false];
