/**
 * TypeScript Language
 * - It is a superset of JavaScript offering more features
 *      - It is not a language on its own but its dependent on JavaScript, since its source code compiles to
 *        JavaScript source code
 * - It provides
 *      - Static Typing to variables, parameters, return types, etc.
 *      - Organization of codes through class, interface, namespace, module, etc.
 *      - Tooling for static type analysis, detecting errors, unused data, unreachable code, debugging, etc.
 */

/**
 * TypeScript Compiler
 * - It uses `tsc` (TypeScript Compiler) for compiling its source code to JavaScript
 *      - It is installed through `npm` preferably at the project level
 * - It uses `tsconfig.json` for its compiling configuration which is generated by `tsc --init`
 *      - Configuration file support inheritance
 *          - Base config can be extended through `extends` options within the config file and then more or override
 *            configuration can be supplied (Compiler must be run where the child configuration file resides)
 */
